# Test-related allows
allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-dbg-in-tests = true
allow-print-in-tests = true
warn-on-all-wildcard-imports = true
missing-docs-in-crate-items = false